#
# Module manifest for module 'PSGet_slmgr-ps'
#
# Generated by: Zafer Balkan
#
# Generated on: 10/10/2023
#

@{

    RootModule        = 'slmgr-ps.psm1'
    ModuleVersion     = '1.5.0'
    GUID              = '7f758ac2-1fc0-4fbd-b894-60f7631ce210'
    Author            = 'Zafer Balkan'
    CompanyName       = 'Zafer Balkan'
    Copyright         = '(c) Zafer Balkan. All rights reserved.'
    Description       = 'An independent community PowerShell alternative for common slmgr.vbs workflows'

    FunctionsToExport = @(
        'Get-WindowsActivation'
        'Install-WindowsLicense'
        'Repair-WindowsLicense'
        'Reset-WindowsActivation'
        'Set-WindowsActivationType'
        'Set-WindowsKmsClient'
        'Start-WindowsActivation'
    )

    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()

    PrivateData       = @{
        PSData = @{
            Tags       = 'windows', 'license', 'slmgr'
            LicenseUri = 'https://choosealicense.com/licenses/mit/'
            ProjectUri = 'https://github.com/zbalkan/slmgr-ps'
            ReleaseNotes = 'Standardized mutation results, batch error identity, provider HRESULT reporting, verification state, and extended activation diagnostics.'
        }
    }
}
